# Generated by Django 4.0.4 on 2022-05-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquary',
            name='title',
            field=models.CharField(default='', max_length=80, verbose_name='질문 제목'),
            preserve_default=False,
        ),
    ]
